version: '3.8'

services:
  rstudio:
    image: custom_rstudio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /rstats-cluster/rstudio/projects/:/home/admin/
      - /rstats-cluster/rstudio/renv/:/home/admin/.local/share/renv/
    environment:
      - USER=${USERNAME?Variable not set}
      - PASSWORD=${HASHED_PASSWORD?Variable not set}
      - ADD=shiny
    networks:
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.rstudio-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.rstudio-http.entrypoints=http
        - traefik.http.routers.rstudio-http.middlewares=https-redirect
        - traefik.http.routers.rstudio-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.rstudio-https.entrypoints=https
        - traefik.http.routers.rstudio-https.tls=true
        - traefik.http.services.rstudio.loadbalancer.server.port=8787

networks:
  traefik-public:
    external: true