version: '3.8'

services:
  rstudio:
    image: tylurp/pirate-rstudio:v0.0.1
    #user: 'root'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOST_HOME?Variable not set}:${RSTUDIO_HOME?Variable not set}
      - ${HOST_RENV?Variable not set}:${RSTUDIO_RENV?Variable not set}
    environment:
      - USER=${USERNAME?Variable not set}
      - PASSWORD=${PASSWORD?Variable not set}
      #- ROOT=TRUE
      #- ADD=shiny
    networks:
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.rstudio-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.rstudio-http.entrypoints=http
        - traefik.http.routers.rstudio-http.middlewares=https-redirect
        - traefik.http.routers.rstudio-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.rstudio-https.entrypoints=https
        - traefik.http.routers.rstudio-https.tls=true
        - traefik.http.routers.rstudio-https.tls.certresolver=le
        - traefik.http.services.rstudio.loadbalancer.server.port=8787

networks:
  traefik-public:
    external: true
