version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2021-06-07T21-40-51Z
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOST_DATA?Variable not set}:/data
    networks:
      - traefik-public
    environment:
      MINIO_ROOT_USER: ${USERNAME?Variable not set}
      MINIO_ROOT_PASSWORD: ${PASSWORD?Variable not set}
    command: server /data
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME?Variable not set}
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.minio-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.minio-http.entrypoints=http
        - traefik.http.routers.minio-http.middlewares=https-redirect
        - traefik.http.routers.minio-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.minio-https.entrypoints=https
        - traefik.http.routers.minio-https.tls=true
        - traefik.http.routers.minio-https.tls.certresolver=le
        - traefik.http.services.minio.loadbalancer.server.port=9000

networks:
  traefik-public:
    external: true
