name: build-prometheus

on:
  push:
    paths:
      - monitor/prometheus/**
      - .github/workflows/build-prometheus.yml

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }} 
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: ./monitor/prometheus
          file: ./monitor/prometheus/Dockerfile_latest
          platforms: linux/arm64,linux/amd64
          push: true
          tags: tylurp/pirate-prometheus:latest
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push v2.27.1
        uses: docker/build-push-action@v2
        with:
          context: ./monitor/prometheus
          file: ./monitor/prometheus/Dockerfile_v2.27.1
          platforms: linux/arm64,linux/amd64
          push: true
          tags: tylurp/pirate-prometheus:v2.27.1
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUBUNAME }}
           DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUBPWD }}
           DOCKERHUB_REPOSITORY: tylurp/pirate-prometheus